vim.api.nvim_create_user_command(
  "TmuxNavigateLeft",
  function()
    require("tmux").navigate("h")
  end,
  {}
)
vim.api.nvim_create_user_command(
  "TmuxNavigateDown",
  function()
    require("tmux").navigate("j")
  end,
  {}
)
vim.api.nvim_create_user_command(
  "TmuxNavigateUp",
  function()
    require("tmux").navigate("k")
  end,
  {}
)
vim.api.nvim_create_user_command(
  "TmuxNavigateRight",
  function()
    require("tmux").navigate("l")
  end,
  {}
)
