[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#767676"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.cursor]
# cursor = "#f2f2f2"
cursor = "#e69500"
text = "#21252b"

[colors.normal]
black = "#21252b"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.primary]
background = "#21252c"
foreground = "#a2a8be"

