#!/usr/bin/awk -f

# gotest - only print failed tests in red
# usage:
#   go test ./... | ./bin/gotest
#

BEGIN {
    RED="\033[31m"
    BRRED="\033[91m"
    NORMAL="\033[0m"
    RED_EMOJI="🔴"   # Red Circle Emoji
}
/FAIL:/  { color=RED; print color RED_EMOJI " " $0 NORMAL; next }
/FAIL/ && !/^[ \t]+/ && $0 ~ /FAIL[ \t]+[^ \t]/ { color=BRRED; print color RED_EMOJI " " $0 NORMAL; next }

# vi: ft=awk
